apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:latest
      # upshift.mirror-registry.qe.devcluster.openshift.com:5000/nginx-unprivileged
        name: guestbook-ui
        ports:
        - containerPort: 80
